Only upload JSON summary files

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -10,7 +10,7 @@
 # - One job to build/test the docker images.
 # - One job to publish the docker image.
 
-name: BenchBase (Java with Maven) (1)
+name: BenchBase (Java with Maven)
 
 on:
   push:
@@ -135,7 +135,7 @@ jobs:
         uses: actions/setup-java@v4
         with:
           java-version: ${{env.JAVA_VERSION}}
-          distribution: 'temurin'    
+          distribution: 'temurin'
 
       - name: Run benchmark
         run: |
@@ -178,11 +178,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: benchmark-results-sqlite-${{ matrix.benchmark }}
-          path: |
-            results/${{ matrix.benchmark }}*.csv
-            results/${{ matrix.benchmark }}*.json
-            results/histograms.json
-            results/monitor
+          path: results/${{ matrix.benchmark }}*-summary.json
           if-no-files-found: error
 
   ## ----------------------------------------------------------------------------------
@@ -271,12 +267,8 @@ jobs:
       - name: Upload benchmark results
         uses: actions/upload-artifact@v4
         with:
-          name: benchmark-results-mariadb-${{ matrix.benchmark }}
-          path: |
-            results/${{ matrix.benchmark }}*.csv
-            results/${{ matrix.benchmark }}*.json
-            results/histograms.json
-            results/monitor
+          name: benchmark-results-sqlite-${{ matrix.benchmark }}
+          path: results/${{ matrix.benchmark }}*-summary.json
           if-no-files-found: error
 
   ## ----------------------------------------------------------------------------------
@@ -385,12 +377,8 @@ jobs:
       - name: Upload benchmark results
         uses: actions/upload-artifact@v4
         with:
-          name: benchmark-results-mysql-${{ matrix.benchmark }}
-          path: |
-            results/${{ matrix.benchmark }}*.csv
-            results/${{ matrix.benchmark }}*.json
-            results/histograms.json
-            results/monitor
+          name: benchmark-results-sqlite-${{ matrix.benchmark }}
+          path: results/${{ matrix.benchmark }}*-summary.json
           if-no-files-found: error
 
   ## ----------------------------------------------------------------------------------
@@ -487,12 +475,300 @@ jobs:
       - name: Upload benchmark results
         uses: actions/upload-artifact@v4
         with:
-          name: benchmark-results-oracle-${{ matrix.benchmark }}
-          path: |
-            results/${{ matrix.benchmark }}*.csv
-            results/${{ matrix.benchmark }}*.json
-            results/histograms.json
-            results/monitor
+          name: benchmark-results-sqlite-${{ matrix.benchmark }}
+          path: results/${{ matrix.benchmark }}*-summary.json
+          if-no-files-found: error
+
+  ## ----------------------------------------------------------------------------------
+  ## POSTGRESQL
+  ## ----------------------------------------------------------------------------------
+  postgresql:
+    needs: package-and-upload
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        benchmark: [ 'auctionmark', 'chbenchmark', 'epinions', 'hyadapt', 'noop', 'otmetrics', 'resourcestresser', 'seats', 'sibench', 'smallbank', 'tatp', 'templated', 'tpcc', 'tpcc-with-reconnects', 'tpch', 'twitter', 'voter', 'wikipedia', 'ycsb' ]
+    steps:
+      # Note: we download just the docker-compose scripts/configs rather than the
+      # whole source code repo for better testing.
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: docker-compose-postgres
+
+      - name: Extract docker-compose artifacts
+        run: |
+          tar xvzf docker-compose-postgres.tar.gz
+
+      # Use docker-compose to start the postgres service so we can modify the
+      # command line args to include extensions.
+      # https://github.com/actions/runner/issues/2139
+      - name: Start custom postgres service
+        run: |
+          ./docker/postgres-latest/up.sh --quiet-pull postgres
+
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: benchbase-postgres
+
+      - name: Extract artifact
+        run: |
+          tar xvzf benchbase-postgres.tgz --strip-components=1
+
+      - name: Delete artifact
+        run: |
+          rm -rf benchbase-postgres.tgz
+
+      - name: Set up JDK
+        uses: actions/setup-java@v4
+        with:
+          java-version: ${{env.JAVA_VERSION}}
+          distribution: 'temurin'
+
+      - name: Run benchmark
+        run: |
+          PGPASSWORD=password dropdb -h localhost -U admin benchbase --if-exists
+          PGPASSWORD=password createdb -h localhost -U admin benchbase
+
+          # For templated benchmarks, we need to preload some data for the test since by design, templated benchmarks do not support the 'load' operation
+          # In this case, we load the tpcc data.
+          if [[ ${{matrix.benchmark}} == templated ]]; then
+            java -jar benchbase.jar -b tpcc -c config/postgres/sample_tpcc_config.xml --create=true --load=true --execute=false --json-histograms results/histograms.json
+            java -jar benchbase.jar -b ${{matrix.benchmark}} -c config/postgres/sample_${{matrix.benchmark}}_config.xml -im 1000 -mt advanced --create=false --load=false --execute=true --json-histograms results/histograms.json
+          elif [[ ${{matrix.benchmark}} == tpcc-with-reconnects ]]; then
+            # See Also: WITH_SERVICE_INTERRUPTIONS=true docker/build-run-benchmark-with-docker.sh
+            java -jar benchbase.jar -b tpcc -c config/postgres/sample_tpcc_config.xml --create=true --load=true
+            (sleep 10 && ./scripts/interrupt-docker-db-service.sh postgres) &
+            java -jar benchbase.jar -b tpcc -c config/postgres/sample_tpcc_config.xml -im 1000 -mt advanced --execute=true --json-histograms results/histograms.json
+          else
+            if [ ${{matrix.benchmark}} == chbenchmark ]; then
+              java -jar benchbase.jar -b tpcc -c config/postgres/sample_tpcc_config.xml --create=true --load=true --execute=false --json-histograms results/histograms.json
+            fi
+            java -jar benchbase.jar -b ${{matrix.benchmark}} -c config/postgres/sample_${{matrix.benchmark}}_config.xml -im 1000 -mt advanced --create=true --load=true --execute=true --json-histograms results/histograms.json
+          fi
+
+          # FIXME: Reduce the error rate so we don't need these overrides.
+          results_benchmark=${{matrix.benchmark}}
+          if [ ${{matrix.benchmark}} == auctionmark ]; then
+              ERRORS_THRESHOLD=0.02
+          elif [ ${{matrix.benchmark}} == tatp ]; then
+              ERRORS_THRESHOLD=0.05
+          elif [ ${{matrix.benchmark}} == tpcc-with-reconnects ]; then
+              ERRORS_THRESHOLD=0.02
+              results_benchmark=tpcc
+          fi
+          ./scripts/check_latest_benchmark_results.sh $results_benchmark
+          ./scripts/check_histogram_results.sh results/histograms.json $ERRORS_THRESHOLD
+
+          # Running the monitor should create at least three files in the 'monitor' directory.
+          if ![ $(find "./results/monitor" -maxdepth 1 -mindepth 1 | wc -l) -gt 2]; then
+            echo "ERROR: Advanced monitoring unsuccessful, file directory and/or appropriate files not created." >&2
+            exit 1
+          fi
+
+      - name: Stop custom postgres service
+        run: |
+          ./docker/postgres-latest/down.sh
+
+      - name: Upload benchmark results
+        uses: actions/upload-artifact@v4
+        with:
+          name: benchmark-results-sqlite-${{ matrix.benchmark }}
+          path: results/${{ matrix.benchmark }}*-summary.json
+          if-no-files-found: error
+
+  ## ----------------------------------------------------------------------------------
+  ## COCKROACHDB
+  ## ----------------------------------------------------------------------------------
+  cockroachdb:
+    needs: package-and-upload
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        # TODO: Add tpcc-with-reconnects benchmark support
+        # TODO: Add chbenchmark benchmark support
+        benchmark: [ 'auctionmark', 'epinions', 'hyadapt', 'noop', 'otmetrics', 'resourcestresser', 'seats', 'sibench', 'smallbank', 'tatp', 'templated', 'tpcc', 'tpch', 'twitter', 'voter', 'wikipedia', 'ycsb' ]
+    services:
+      cockroach: # https://hub.docker.com/repository/docker/timveil/cockroachdb-single-node
+        image: timveil/cockroachdb-single-node:latest
+        env:
+          DATABASE_NAME: benchbase
+          # TODO: Expand for additional config adjustments (See Also: #405, #519, #525)
+          MEMORY_SIZE: .75
+        ports:
+          - 26257:26257
+    steps:
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: benchbase-cockroachdb
+
+      - name: Extract artifact
+        run: |
+          tar xvzf benchbase-cockroachdb.tgz --strip-components=1
+
+      - name: Delete artifact
+        run: |
+          rm -rf benchbase-cockroachdb.tgz
+
+      - name: Set up JDK
+        uses: actions/setup-java@v4
+        with:
+          java-version: ${{env.JAVA_VERSION}}
+          distribution: 'temurin'
+
+      - name: Run benchmark
+        run: |
+          # For templated benchmarks, we need to preload some data for the test since by design, templated benchmarks do not support the 'load' operation
+          # In this case, we load the tpcc data.
+          if [[ ${{matrix.benchmark}} == templated ]]; then
+            java -jar benchbase.jar -b tpcc -c config/cockroachdb/sample_tpcc_config.xml --create=true --load=true --execute=false --json-histograms results/histograms.json
+            java -jar benchbase.jar -b ${{matrix.benchmark}} -c config/cockroachdb/sample_${{matrix.benchmark}}_config.xml --create=false --load=false --execute=true --json-histograms results/histograms.json
+          elif [[ ${{matrix.benchmark}} == tpcc-with-reconnects ]]; then
+            # See Also: WITH_SERVICE_INTERRUPTIONS=true docker/build-run-benchmark-with-docker.sh
+            java -jar benchbase.jar -b tpcc -c config/cockroachdb/sample_tpcc_config.xml --create=true --load=true
+            (sleep 10 && ./scripts/interrupt-docker-db-service.sh cockroachdb) &
+            java -jar benchbase.jar -b tpcc -c config/cockroachdb/sample_tpcc_config.xml --execute=true --json-histograms results/histograms.json
+          else
+            if [ ${{matrix.benchmark}} == chbenchmark ]; then
+              java -jar benchbase.jar -b tpcc -c config/cockroachdb/sample_tpcc_config.xml --create=true --load=true --execute=false --json-histograms results/histograms.json
+            fi
+            java -jar benchbase.jar -b ${{matrix.benchmark}} -c config/cockroachdb/sample_${{matrix.benchmark}}_config.xml --create=true --load=true --execute=true --json-histograms results/histograms.json
+          fi
+
+          # FIXME: Reduce the error rate so we don't need these overrides.
+          results_benchmark=${{matrix.benchmark}}
+          if [ ${{matrix.benchmark}} == auctionmark ]; then
+              ERRORS_THRESHOLD=0.02
+          elif [ ${{matrix.benchmark}} == tatp ]; then
+              ERRORS_THRESHOLD=0.05
+          elif [ ${{matrix.benchmark}} == tpcc-with-reconnects ]; then
+              ERRORS_THRESHOLD=0.02
+              results_benchmark=tpcc
+          fi
+          ./scripts/check_latest_benchmark_results.sh $results_benchmark
+          ./scripts/check_histogram_results.sh results/histograms.json $ERRORS_THRESHOLD
+
+      - name: Upload benchmark results
+        uses: actions/upload-artifact@v4
+        with:
+          name: benchmark-results-sqlite-${{ matrix.benchmark }}
+          path: results/${{ matrix.benchmark }}*-summary.json
+          if-no-files-found: error
+
+  ## ----------------------------------------------------------------------------------
+  ## MSSQL
+  ## ----------------------------------------------------------------------------------
+  sqlserver:
+    needs: package-and-upload
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        # TODO: add auctionmark and seats benchmark
+        benchmark: [ 'epinions', 'hyadapt', 'noop', 'otmetrics', 'resourcestresser', 'sibench', 'smallbank', 'tatp', 'templated', 'tpcc', 'tpcc-with-reconnects', 'tpch', 'twitter', 'voter', 'wikipedia', 'ycsb' ]
+    services:
+      sqlserver:
+        image: mcr.microsoft.com/mssql/server:latest
+        env:
+          ACCEPT_EULA: Y
+          SA_PASSWORD: SApassword1
+        options: >-
+          --health-cmd "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P SApassword1 -b -Q 'SELECT 1;'"
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
+        ports:
+          - 1433:1433
+    steps:
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: benchbase-sqlserver
+
+      - name: Extract artifact
+        run: |
+          tar xvzf benchbase-sqlserver.tgz --strip-components=1
+
+      - name: Delete artifact
+        run: |
+          rm -rf benchbase-sqlserver.tgz
+
+      - name: Set up JDK
+        uses: actions/setup-java@v4
+        with:
+          java-version: ${{env.JAVA_VERSION}}
+          distribution: 'temurin'
+
+      - name: Cleanup database
+        uses: docker://mcr.microsoft.com/mssql-tools:latest
+        with:
+          entrypoint: /opt/mssql-tools/bin/sqlcmd
+          args: -U sa -P SApassword1 -S sqlserver -b -Q "DROP DATABASE IF EXISTS benchbase;"
+
+      - name: Setup database
+        uses: docker://mcr.microsoft.com/mssql-tools:latest
+        with:
+          entrypoint: /opt/mssql-tools/bin/sqlcmd
+          args: -U sa -P SApassword1 -S sqlserver -b -Q "CREATE DATABASE benchbase;"
+
+      - name: Setup login
+        uses: docker://mcr.microsoft.com/mssql-tools:latest
+        with:
+          entrypoint: /opt/mssql-tools/bin/sqlcmd
+          args: -U sa -P SApassword1 -S sqlserver -Q "CREATE LOGIN benchuser01 WITH PASSWORD='P@ssw0rd';"
+
+      - name: Setup access
+        uses: docker://mcr.microsoft.com/mssql-tools:latest
+        with:
+          entrypoint: /opt/mssql-tools/bin/sqlcmd
+          args: -U sa -P SApassword1 -S sqlserver -b -Q "USE benchbase; CREATE USER benchuser01 FROM LOGIN benchuser01; EXEC sp_addrolemember 'db_owner', 'benchuser01';"
+
+      - name: Run benchmark
+        # Note: user/pass should match those used in sample configs.
+        run: |
+          # For templated benchmarks, we need to preload some data for the test since by design, templated benchmarks do not support the 'load' operation
+          # In this case, we load the tpcc data.
+          if [[ ${{matrix.benchmark}} == templated ]]; then
+            java -jar benchbase.jar -b tpcc -c config/sqlserver/sample_tpcc_config.xml --create=true --load=true --execute=false --json-histograms results/histograms.json
+            java -jar benchbase.jar -b ${{matrix.benchmark}} -c config/sqlserver/sample_${{matrix.benchmark}}_config.xml -im 1000 -mt advanced  --create=false --load=false --execute=true --json-histograms results/histograms.json
+          elif [[ ${{matrix.benchmark}} == tpcc-with-reconnects ]]; then
+            # See Also: WITH_SERVICE_INTERRUPTIONS=true docker/build-run-benchmark-with-docker.sh
+            java -jar benchbase.jar -b tpcc -c config/sqlserver/sample_tpcc_config.xml --create=true --load=true
+            (sleep 10 && ./scripts/interrupt-docker-db-service.sh sqlserver) &
+            java -jar benchbase.jar -b tpcc -c config/sqlserver/sample_tpcc_config.xml -im 1000 -mt advanced --execute=true --json-histograms results/histograms.json
+          else
+            if [ ${{matrix.benchmark}} == chbenchmark ]; then
+              java -jar benchbase.jar -b tpcc -c config/sqlserver/sample_tpcc_config.xml --create=true --load=true --execute=false --json-histograms results/histograms.json
+            fi
+            java -jar benchbase.jar -b ${{matrix.benchmark}} -c config/sqlserver/sample_${{matrix.benchmark}}_config.xml -im 1000 -mt advanced --create=true --load=true --execute=true --json-histograms results/histograms.json
+          fi
+
+          # FIXME: Reduce the error rate so we don't need these overrides.
+          results_benchmark=${{matrix.benchmark}}
+          if [ ${{matrix.benchmark}} == tatp ]; then
+              ERRORS_THRESHOLD=0.05
+          elif [ ${{matrix.benchmark}} == tpcc-with-reconnects ]; then
+              ERRORS_THRESHOLD=0.02
+              results_benchmark=tpcc
+          fi
+          ./scripts/check_latest_benchmark_results.sh $results_benchmark
+          ./scripts/check_histogram_results.sh results/histograms.json $ERRORS_THRESHOLD
+
+          # Running the monitor should create at least three files in the 'monitor' directory.
+          if ![ $(find "./results/monitor" -maxdepth 1 -mindepth 1 | wc -l) -gt 2]; then
+            echo "ERROR: Advanced monitoring unsuccessful, file directory and/or appropriate files not created." >&2
+            exit 1
+          fi
+
+      - name: Upload benchmark results
+        uses: actions/upload-artifact@v4
+        with:
+          name: benchmark-results-sqlite-${{ matrix.benchmark }}
+          path: results/${{ matrix.benchmark }}*-summary.json
           if-no-files-found: error
 
   ## ----------------------------------------------------------------------------------
