Update maven2.yml

diff --git a/.github/workflows/maven2.yml b/.github/workflows/maven2.yml
--- a/.github/workflows/maven2.yml
+++ b/.github/workflows/maven2.yml
@@ -199,11 +199,29 @@ jobs:
         run: |
           ./docker/postgres-latest/down.sh
 
+      - name: Get result file paths
+        id: get_result_files
+        run: |
+          config_file=$(ls -1t results/${{ matrix.benchmark }}_*.config.xml | head -n1)
+          if [ -z "$config_file" ]; then
+            echo "ERROR: Failed to find ${{ matrix.benchmark }} benchmark results files." >&2
+            exit 1
+          fi
+          ts=$(basename "$config_file" | sed -e "s/^${{ matrix.benchmark }}_//" -e 's/\.config\.xml//')
+          summary_json="results/${{ matrix.benchmark }}_${ts}.summary.json"
+          echo "config_file=$config_file" >> $GITHUB_OUTPUT
+          echo "summary_json=$summary_json" >> $GITHUB_OUTPUT
+
       - name: Upload benchmark results
         uses: actions/upload-artifact@v4
         with:
-          name: benchmark-results-postgressql-${{ matrix.benchmark }}
-          path: results/${{matrix.benchmark}}
+          name: benchmark-results-${{ matrix.benchmark }}
+          path: |
+            results/histograms.json
+            ${{ steps.get_result_files.outputs.config_file }}
+            ${{ steps.get_result_files.outputs.summary_json }}
+            results/${{ matrix.benchmark }}*.csv
+            results/monitor/
           if-no-files-found: error
 
   ## ----------------------------------------------------------------------------------
@@ -279,11 +297,29 @@ jobs:
           ./scripts/check_latest_benchmark_results.sh $results_benchmark
           ./scripts/check_histogram_results.sh results/histograms.json $ERRORS_THRESHOLD
 
+      - name: Get result file paths
+        id: get_result_files
+        run: |
+          config_file=$(ls -1t results/${{ matrix.benchmark }}_*.config.xml | head -n1)
+          if [ -z "$config_file" ]; then
+            echo "ERROR: Failed to find ${{ matrix.benchmark }} benchmark results files." >&2
+            exit 1
+          fi
+          ts=$(basename "$config_file" | sed -e "s/^${{ matrix.benchmark }}_//" -e 's/\.config\.xml//')
+          summary_json="results/${{ matrix.benchmark }}_${ts}.summary.json"
+          echo "config_file=$config_file" >> $GITHUB_OUTPUT
+          echo "summary_json=$summary_json" >> $GITHUB_OUTPUT
+
       - name: Upload benchmark results
         uses: actions/upload-artifact@v4
         with:
-          name: benchmark-results-cockroachdb-${{ matrix.benchmark }}
-          path: results/${{matrix.benchmark}}
+          name: benchmark-results-${{ matrix.benchmark }}
+          path: |
+            results/histograms.json
+            ${{ steps.get_result_files.outputs.config_file }}
+            ${{ steps.get_result_files.outputs.summary_json }}
+            results/${{ matrix.benchmark }}*.csv
+            results/monitor/
           if-no-files-found: error
 
   ## ----------------------------------------------------------------------------------
@@ -391,11 +427,29 @@ jobs:
             exit 1
           fi
           
+      - name: Get result file paths
+        id: get_result_files
+        run: |
+          config_file=$(ls -1t results/${{ matrix.benchmark }}_*.config.xml | head -n1)
+          if [ -z "$config_file" ]; then
+            echo "ERROR: Failed to find ${{ matrix.benchmark }} benchmark results files." >&2
+            exit 1
+          fi
+          ts=$(basename "$config_file" | sed -e "s/^${{ matrix.benchmark }}_//" -e 's/\.config\.xml//')
+          summary_json="results/${{ matrix.benchmark }}_${ts}.summary.json"
+          echo "config_file=$config_file" >> $GITHUB_OUTPUT
+          echo "summary_json=$summary_json" >> $GITHUB_OUTPUT
+
       - name: Upload benchmark results
         uses: actions/upload-artifact@v4
         with:
-          name: benchmark-results-mssql-${{ matrix.benchmark }}
-          path: results/${{matrix.benchmark}}
+          name: benchmark-results-${{ matrix.benchmark }}
+          path: |
+            results/histograms.json
+            ${{ steps.get_result_files.outputs.config_file }}
+            ${{ steps.get_result_files.outputs.summary_json }}
+            results/${{ matrix.benchmark }}*.csv
+            results/monitor/
           if-no-files-found: error
 
   ## ----------------------------------------------------------------------------------
